dist: bionic

language: generic

cache:
  pip: true
  directories:
  - "$HOME/db/"
env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: "travis@travis-ci.org"
  - TRAVIS_REPO_SLUG: Clefspeare13/pornhosts
  - GIT_BRANCH: $"{TRAVIS_BRANCH}"
  - TZ: UTC
  - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/travis/"
  - PYFUNCEBLE_AUTO_CONFIGURATION: yes
  #- DEBUG_PYFUNCEBLE: true
  #- DEBUG_PYFUNCEBLE_ON_SCREEN: true
  - PYTHON_VERSION: 3.8.2
  #- secure: 
addons:
  mariadb: '10.4'
  apt:
    packages:
    - dos2unix
    - msttcorefonts
    - lsof

install:
  - sudo bash "${TRAVIS_BUILD_DIR}/travis/setup_recursor.sh"
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python --version --version
  - pip --version
  - conda --version
  - pip -q install pyfunceble-dev ultimate-hosts-blacklist-whitelist-dev

git:
  depth: 2
branches:
  only:
  - master

script:
  - sudo systemctl restart mysql.service
  - sudo mysql -u root -h localhost -e "CREATE DATABASE PyFunceble DEFAULT CHARACTER
    SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  - sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  - sudo mysql -u root -h localhost -e "CREATE USER 'PyFunceble'@'localhost' IDENTIFIED
    BY 'PyFunceble';"
  - sudo mysql -u root -h localhost -e "GRANT ALL PRIVILEGES ON *.* TO 'PyFunceble'@'localhost';"
  - if [ -f ${HOME}/db/pyfunceble.sql ]; then sudo mysql --user=PyFunceble --password=PyFunceble
    PyFunceble < ${HOME}/db/pyfunceble.sql; fi
  #- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash 'toolbox/GenerateHostsFile.sh'; fi
    # This script ain't ready yet
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash './travis/run_on_pull_requests''; fi
